<?php /** @var $block SR\UpsShip\Block\Adminhtml\Order\View\Ups */ ?>
<?php if ($block->canShow()): ?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?php /* @escapeNotVerified */ echo __('PickUP Location Information') ?></span>
        </div>
        <div class="admin__page-section-content">
            <div><strong><?php echo $block->getUpsLocationId(); ?></strong></div>
            <?php foreach ($block->getUpsLocationDetails() as $detailName => $detail): ?>
                <div><?php /* @escapeNotVerified */ echo $detail; ?></div>
            <?php endforeach; ?>
        </div>
    </section>
<?php endif; ?>
