<div id="upsship-component" data-bind="scope:'ups-ship-block'" class="block">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "#upsship-component": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "ups-ship-block": {
                        "component": "SR_UpsShip/js/view/paypal/order/review/ups-ship-block",
                        "options" : {
                            "shippingAddress" : <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getShippingAddress()); ?>
                        }
                    }
                }
            }
        }
    }
</script>
